### ISSUE TITLE
Referencing a source in a model injects the source name as the schema

### ISSUE THREAD

**Issue by ravjotbrar** [dremio/dbt-dremio#99]
Source YAML:

```
version: 2

sources:
  - name: mysource
    database: s3
    tables:
      - name: NYC_TRIPS_PARQUET
```

Model sql file:

```
with mytrip as (
select * from  {{ source('mysource','NYC_TRIPS_PARQUET') }}
)
select * from mytrip
```

Resulting query:

```
with mytrip as (
select * from  "s3"."mysource"."NYC_TRIPS_PARQUET"
)

```
Expectation:

```
with mytrip as (
select * from  "s3"."NYC_TRIPS_PARQUET"
)

```

**Comment by fabrice-etanchaud** [comment]
Hi @ravjotbrar , it may not be a bug, but a standard dbt's behavior : [source schema default value](https://docs.getdbt.com/reference/resource-properties/schema#definition)
Could you please try with 👍 

```
version: 2

sources:
  - name: mysource
    database: s3
    schema: no_schema
    tables:
      - name: NYC_TRIPS_PARQUET

```

Best regards, Fabrice
